package com.derangementinc.gradespeedmobile.enums;

public enum Errors {
	NONE,
	NO_WIFI,
	INVALID_USER_PASS,
	INVALID_DISTRICT_URL,
	ENCODING_ERROR,
	FOUND_SIBLINGS,
	COULD_NOT_PARSE_PAGE,
	COULD_NOT_FIND_GRADES_PAGE,
	NO_CURRENT_SIBLING,
	COULD_NOT_PARSE_FOR_OTHER_STUDENTS,
	COULD_NOT_PARSE_FOR_GRADES,
	COULD_NOT_PARSE_FOR_SPECIFIC_GRADES,
	UNKNOWN_HTTP_ERROR,
	DOING_HTTPS_REDIRECT,
	HTTP_CAPTIVE_PORTAL,
	HTTP_NOT_FOUND,
	COULD_NOT_REACH_PAGE,
}